apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 2 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: bhavatharinione/world:one
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          command: ["java", "-jar", "app.jar"]
          workingDir: /opt
---
apiVersion: v1
kind: Service
metadata:
  name: helloworldservice
spec:
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Port on the container
  type: NodePort
